import '@/styles/globals.css';
import { Noto_Sans_JP } from 'next/font/google';
import type { Metadata } from 'next';

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'], variable: '--font-noto-sans-jp' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ja'>
      <body className={notoSansJP.className}>{children}</body>
    </html>
  );
}
